### ISSUE TITLE
edit and save ability

### ISSUE THREAD

**Issue by AntHJ** [Princess-of-Sleeping/psp2waveviewer#1]
It would be nice to be able to not only preview the wave but also have some kind of GUI to change the values so you could create / tweak the look and style of the waveform and then save them as presets

**Comment by Havocking1992** [comment]
> It would be nice to be able to not only preview the wave but also have some kind of GUI to change the values so you could create / tweak the look and style of the waveform and then save them as presets

I am full 100% for this, it will be good to have ability to change parameters in realtime with some descriptions , something like transparent floating window. People don't want to mess with it like me, as far as i know i am only one doing it. I can imagine that 90% of people just said "nah, too hard" when they read my tutorial lol

**Comment by Princess-of-Sleeping** [comment]
I thought about this feature, but it is not currently possible due to technical reasons.
1. vitasdk does not support Paf GUI programming.
2. I don't know if GUI with vita2d based on Paf Gxm context is possible.

**Comment by Princess-of-Sleeping** [comment]
[psp2wpp-remote-conf](https://github.com/Princess-of-Sleeping/psp2wpp-remote-conf) has been released. Please consider using it.

If you have any questions, please re-open the issue again.

Thank you :)

**Comment by Havocking1992** [comment]
> I thought about this feature, but it is not currently possible due to technical reasons.
> 
> 1. vitasdk does not support Paf GUI programming.
> 2. I don't know if GUI with vita2d based on Paf Gxm context is possible.

I was thinking about something similiar like PSVShell, will it be too hard to implement?

**Comment by Princess-of-Sleeping** [comment]
Yes. it's too hard.

**Comment by Havocking1992** [comment]
Understood 👍🏻
